export { membersRepo } from "./members";
export { insurersRepo } from "./insurers";
export { assetsRepo } from "./assets";
export { policiesRepo } from "./policies";
export { beneficiariesRepo } from "./beneficiaries";
export { paymentsRepo } from "./payments";
export { cashValuesRepo } from "./cashValues";
export { policyExtensionsRepo } from "./policyExtensions";
export { settingsRepo } from "./settings";
