name = "surety"
main = "src/index.ts"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB_PROD"
database_name = "surety-db"
database_id = "9e57f832-0c6f-4456-8706-612f2965a66c"

[[d1_databases]]
binding = "DB_DEV"
database_name = "surety-db-dev"
database_id = "779124b1-8e5d-4823-8065-035871e591d0"
